package cn.et.food.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import cn.et.food.entity.Myfood;
import cn.et.food.entity.MyfoodExample;
import cn.et.food.entity.MyfoodExample.Criteria;
import cn.et.food.entity.MyfoodExample.Criterion;

public class MyfoodSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String countByExample(MyfoodExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("myfood");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String deleteByExample(MyfoodExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("myfood");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String insertSelective(Myfood record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("myfood");
        
        if (record.getFoodid() != null) {
            sql.VALUES("foodid", "#{foodid,jdbcType=INTEGER}");
        }
        
        if (record.getFoodname() != null) {
            sql.VALUES("foodname", "#{foodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=VARCHAR}");
        }
        
        if (record.getImagepath() != null) {
            sql.VALUES("imagepath", "#{imagepath,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String selectByExample(MyfoodExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("foodid");
        } else {
            sql.SELECT("foodid");
        }
        sql.SELECT("foodname");
        sql.SELECT("price");
        sql.SELECT("imagepath");
        sql.FROM("myfood");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Myfood record = (Myfood) parameter.get("record");
        MyfoodExample example = (MyfoodExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("myfood");
        
        if (record.getFoodid() != null) {
            sql.SET("foodid = #{record.foodid,jdbcType=INTEGER}");
        }
        
        if (record.getFoodname() != null) {
            sql.SET("foodname = #{record.foodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        }
        
        if (record.getImagepath() != null) {
            sql.SET("imagepath = #{record.imagepath,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("myfood");
        
        sql.SET("foodid = #{record.foodid,jdbcType=INTEGER}");
        sql.SET("foodname = #{record.foodname,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        sql.SET("imagepath = #{record.imagepath,jdbcType=VARCHAR}");
        
        MyfoodExample example = (MyfoodExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String updateByPrimaryKeySelective(Myfood record) {
        SQL sql = new SQL();
        sql.UPDATE("myfood");
        
        if (record.getFoodname() != null) {
            sql.SET("foodname = #{foodname,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=VARCHAR}");
        }
        
        if (record.getImagepath() != null) {
            sql.SET("imagepath = #{imagepath,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("foodid = #{foodid,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    protected void applyWhere(SQL sql, MyfoodExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}