package cn.et.food.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.food.entity.Myfood;
import cn.et.food.entity.MyfoodExample;

public interface MyfoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @SelectProvider(type=MyfoodSqlProvider.class, method="countByExample")
    long countByExample(MyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @DeleteProvider(type=MyfoodSqlProvider.class, method="deleteByExample")
    int deleteByExample(MyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @Delete({
        "delete from myfood",
        "where foodid = #{foodid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer foodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @Insert({
        "insert into myfood (foodid, foodname, ",
        "price, imagepath)",
        "values (#{foodid,jdbcType=INTEGER}, #{foodname,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=VARCHAR}, #{imagepath,jdbcType=VARCHAR})"
    })
    int insert(Myfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @InsertProvider(type=MyfoodSqlProvider.class, method="insertSelective")
    int insertSelective(Myfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @SelectProvider(type=MyfoodSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="foodid", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foodname", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR),
        @Result(column="imagepath", property="imagepath", jdbcType=JdbcType.VARCHAR)
    })
    List<Myfood> selectByExampleWithRowbounds(MyfoodExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @SelectProvider(type=MyfoodSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="foodid", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foodname", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR),
        @Result(column="imagepath", property="imagepath", jdbcType=JdbcType.VARCHAR)
    })
    List<Myfood> selectByExample(MyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @Select({
        "select",
        "foodid, foodname, price, imagepath",
        "from myfood",
        "where foodid = #{foodid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="foodid", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foodname", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.VARCHAR),
        @Result(column="imagepath", property="imagepath", jdbcType=JdbcType.VARCHAR)
    })
    Myfood selectByPrimaryKey(Integer foodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @UpdateProvider(type=MyfoodSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Myfood record, @Param("example") MyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @UpdateProvider(type=MyfoodSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Myfood record, @Param("example") MyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @UpdateProvider(type=MyfoodSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Myfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myfood
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    @Update({
        "update myfood",
        "set foodname = #{foodname,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=VARCHAR},",
          "imagepath = #{imagepath,jdbcType=VARCHAR}",
        "where foodid = #{foodid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Myfood record);
}