package cn.et.food.entity;

public class Myfood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myfood.foodid
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myfood.foodname
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myfood.price
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myfood.imagepath
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    private String imagepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myfood.foodid
     *
     * @return the value of myfood.foodid
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myfood.foodid
     *
     * @param foodid the value for myfood.foodid
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myfood.foodname
     *
     * @return the value of myfood.foodname
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myfood.foodname
     *
     * @param foodname the value for myfood.foodname
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myfood.price
     *
     * @return the value of myfood.price
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myfood.price
     *
     * @param price the value for myfood.price
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myfood.imagepath
     *
     * @return the value of myfood.imagepath
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myfood.imagepath
     *
     * @param imagepath the value for myfood.imagepath
     *
     * @mbg.generated Sat Dec 09 16:10:19 CST 2017
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath == null ? null : imagepath.trim();
    }
}